version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pass Firebase authentication information as build arguments
        # These are mapped from .env.local or environment variables
        FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
        FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
    ports:
      - "8080:8080"
    environment:
      # Additional environment variables that might be needed at runtime
      # but are not explicitly defined in .env.local
      FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
    volumes:
      # Mount source code for hot reloading during development
      - ./src:/app/src
      - ./public:/app/public
      # Mount credential files
      - ./pingo-456817-ddc416f0394a.json:/app/pingo-456817-ddc416f0394a.json:ro
      - ./pingo-456817-firebase-adminsdk-fbsvc-94b63a9da5.json:/app/pingo-456817-firebase-adminsdk-fbsvc-94b63a9da5.json:ro
    env_file:
      # Load runtime environment variables from .env.local
      - .env.local
